baseurl             = "http://rossmcf.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-GB"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Ross McFarlane"
title               = "Ross McFarlane"
pygmentsuseclasses  = true
pygmentsUseClassic  = true
#pygmentsCodeFences  = true
# disqusshortname     = "" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-93936167-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author                 = "Ross McFarlane"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "2 Jan, 2006"
dateformfull           = "Mon 2 Jan 2006 15:04:05 MST"
description            = "The personal home page of Ross McFarlane"
email                  = ""
extracssfiles          = []       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/rossmcf"
highlightjs            = true
lang                   = "en"
#linkedin               = "//linkedin.com/in/you"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/rossmcf"
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set

avatar                 = "img/profile2.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # do not use in the same time as avatar

[mediaTypes]
[mediaTypes."application/atom"]
suffix = "xml"

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "index"
isPlainText = false

[outputs]
home = [ "HTML", "Atom" ]
